# Generated by Django 5.1 on 2024-08-16 19:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(default='', max_length=150)),
                ('email_usuario', models.EmailField(default='', max_length=254)),
                ('idade_usuario', models.IntegerField(default=0)),
            ],
        ),
    ]
